// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOm5DSVwrJvTilIJqJGIHIVuFRTXs_jWU',
    appId: '1:850767534789:web:bcffc67054ff28b5f56eac',
    messagingSenderId: '850767534789',
    projectId: 'gamerzz-8d9a3',
    authDomain: 'gamerzz-8d9a3.firebaseapp.com',
    storageBucket: 'gamerzz-8d9a3.appspot.com',
    measurementId: 'G-CNX9RNQ58K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_3UZJmKJNLKNCQcbfjqmMtKJpNfUtGI',
    appId: '1:850767534789:android:494464ad4137f092f56eac',
    messagingSenderId: '850767534789',
    projectId: 'gamerzz-8d9a3',
    storageBucket: 'gamerzz-8d9a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVRTSk4i0aY6E3fnSHP5iShB4rppwN0Ik',
    appId: '1:850767534789:ios:a2fe47c17776c152f56eac',
    messagingSenderId: '850767534789',
    projectId: 'gamerzz-8d9a3',
    storageBucket: 'gamerzz-8d9a3.appspot.com',
    iosBundleId: 'com.kwapad.gamerz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVRTSk4i0aY6E3fnSHP5iShB4rppwN0Ik',
    appId: '1:850767534789:ios:a2fe47c17776c152f56eac',
    messagingSenderId: '850767534789',
    projectId: 'gamerzz-8d9a3',
    storageBucket: 'gamerzz-8d9a3.appspot.com',
    iosBundleId: 'com.kwapad.gamerz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOm5DSVwrJvTilIJqJGIHIVuFRTXs_jWU',
    appId: '1:850767534789:web:f45e1df2de501a51f56eac',
    messagingSenderId: '850767534789',
    projectId: 'gamerzz-8d9a3',
    authDomain: 'gamerzz-8d9a3.firebaseapp.com',
    storageBucket: 'gamerzz-8d9a3.appspot.com',
    measurementId: 'G-3TL690JHRC',
  );

}